# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt5first.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 660)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(10, 10, 91, 81))
        self.pushButton_start.setStyleSheet("font: 75 10pt \"Microsoft YaHei\";")
        self.pushButton_start.setObjectName("pushButton_start")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(579, 360, 371, 102))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.speedtext = QtWidgets.QLabel(self.layoutWidget)
        self.speedtext.setStyleSheet("font: 75 italic 10pt \"3ds\";")
        self.speedtext.setObjectName("speedtext")
        self.gridLayout_2.addWidget(self.speedtext, 0, 0, 1, 1)
        self.dial_speed = QtWidgets.QDial(self.layoutWidget)
        self.dial_speed.setObjectName("dial_speed")
        self.gridLayout_2.addWidget(self.dial_speed, 0, 1, 3, 1)
        self.progressBar_speed = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar_speed.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.progressBar_speed.setProperty("value", 24)
        self.progressBar_speed.setObjectName("progressBar_speed")
        self.gridLayout_2.addWidget(self.progressBar_speed, 1, 0, 1, 1)
        self.horizontalSlider_speed = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSlider_speed.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_speed.setObjectName("horizontalSlider_speed")
        self.gridLayout_2.addWidget(self.horizontalSlider_speed, 2, 0, 1, 1)
        self.pushButton_forword = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_forword.setGeometry(QtCore.QRect(160, 140, 71, 61))
        self.pushButton_forword.setStyleSheet("font: 75 10pt \"Microsoft YaHei\";")
        self.pushButton_forword.setObjectName("pushButton_forword")
        self.pushButton_left = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_left.setGeometry(QtCore.QRect(70, 220, 71, 61))
        self.pushButton_left.setStyleSheet("font: 75 10pt \"Microsoft YaHei\";")
        self.pushButton_left.setObjectName("pushButton_left")
        self.pushButton_right = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_right.setGeometry(QtCore.QRect(250, 220, 71, 61))
        self.pushButton_right.setStyleSheet("font: 75 10pt \"Microsoft YaHei\";")
        self.pushButton_right.setObjectName("pushButton_right")
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_back.setGeometry(QtCore.QRect(160, 300, 71, 61))
        self.pushButton_back.setStyleSheet("font: 75 10pt \"Microsoft YaHei\";")
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_up = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_up.setGeometry(QtCore.QRect(70, 420, 71, 61))
        self.pushButton_up.setStyleSheet("font: 75 10pt \"Microsoft YaHei\";")
        self.pushButton_up.setObjectName("pushButton_up")
        self.pushButton_down = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_down.setGeometry(QtCore.QRect(250, 420, 71, 61))
        self.pushButton_down.setStyleSheet("font: 75 10pt \"Microsoft YaHei\";")
        self.pushButton_down.setObjectName("pushButton_down")
        self.pushButton_rz1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_rz1.setGeometry(QtCore.QRect(70, 520, 71, 61))
        self.pushButton_rz1.setStyleSheet("font: 75 10pt \"Microsoft YaHei\";")
        self.pushButton_rz1.setObjectName("pushButton_rz1")
        self.pushButton_rz2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_rz2.setGeometry(QtCore.QRect(250, 520, 71, 61))
        self.pushButton_rz2.setStyleSheet("font: 75 10pt \"Microsoft YaHei\";")
        self.pushButton_rz2.setObjectName("pushButton_rz2")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(580, 480, 371, 102))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.distance = QtWidgets.QLabel(self.layoutWidget1)
        self.distance.setStyleSheet("font: 75 italic 10pt \"3ds\";")
        self.distance.setObjectName("distance")
        self.gridLayout.addWidget(self.distance, 0, 0, 1, 1)
        self.dial_distance = QtWidgets.QDial(self.layoutWidget1)
        self.dial_distance.setObjectName("dial_distance")
        self.gridLayout.addWidget(self.dial_distance, 0, 1, 3, 1)
        self.progressBar_distance = QtWidgets.QProgressBar(self.layoutWidget1)
        self.progressBar_distance.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.progressBar_distance.setProperty("value", 24)
        self.progressBar_distance.setObjectName("progressBar_distance")
        self.gridLayout.addWidget(self.progressBar_distance, 1, 0, 1, 1)
        self.horizontalSlider_distance = QtWidgets.QSlider(self.layoutWidget1)
        self.horizontalSlider_distance.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_distance.setObjectName("horizontalSlider_distance")
        self.gridLayout.addWidget(self.horizontalSlider_distance, 2, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(150, 210, 91, 81))
        self.graphicsView.setObjectName("graphicsView")
        self.label_Z = QtWidgets.QLabel(self.centralwidget)
        self.label_Z.setGeometry(QtCore.QRect(170, 430, 51, 41))
        self.label_Z.setObjectName("label_Z")
        self.label_rz = QtWidgets.QLabel(self.centralwidget)
        self.label_rz.setGeometry(QtCore.QRect(170, 530, 51, 41))
        self.label_rz.setObjectName("label_rz")
        self.pushButton_reset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reset.setGeometry(QtCore.QRect(890, 270, 61, 61))
        self.pushButton_reset.setObjectName("pushButton_reset")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1036, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_start.setText(_translate("MainWindow", "PushButton"))
        self.speedtext.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">speed</span></p></body></html>"))
        self.pushButton_forword.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_left.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_right.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_back.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_up.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_down.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_rz1.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_rz2.setText(_translate("MainWindow", "PushButton"))
        self.distance.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">distance</span></p></body></html>"))
        self.label_Z.setText(_translate("MainWindow", "TextLabel"))
        self.label_rz.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_reset.setText(_translate("MainWindow", "PushButton"))

